// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2uRWKyLrOIDClhVuKwSiAaxZ5GMekyQ',
    appId: '1:886596265618:web:5fefe800a159a239ea684b',
    messagingSenderId: '886596265618',
    projectId: 'todo-app-fd638',
    authDomain: 'todo-app-fd638.firebaseapp.com',
    storageBucket: 'todo-app-fd638.appspot.com',
    measurementId: 'G-L2XTXY0SFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-69RwqQJenBhlvgklFLl87M8AQRc71Q',
    appId: '1:886596265618:android:b9c23a5256da0326ea684b',
    messagingSenderId: '886596265618',
    projectId: 'todo-app-fd638',
    storageBucket: 'todo-app-fd638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfnyYx8gC5t2oh9VK3r7m_PtHMXOsbOXw',
    appId: '1:886596265618:ios:449e11b65ee9df63ea684b',
    messagingSenderId: '886596265618',
    projectId: 'todo-app-fd638',
    storageBucket: 'todo-app-fd638.appspot.com',
    iosBundleId: 'com.example.todoAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfnyYx8gC5t2oh9VK3r7m_PtHMXOsbOXw',
    appId: '1:886596265618:ios:1bf64105fdd7a892ea684b',
    messagingSenderId: '886596265618',
    projectId: 'todo-app-fd638',
    storageBucket: 'todo-app-fd638.appspot.com',
    iosBundleId: 'com.example.todoAppFirebase.RunnerTests',
  );
}
